project:
  type: website
  output-dir: docs

website:
  title: "Shea Munson's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



